export { default as Home } from './icn_home.svg?react'
export { default as Look } from './icn_look.svg?react'
export { default as Music } from './icn_music.svg?react'
export { default as Person } from './icn_person.svg?react'
export { default as Gallery } from './icn_gallery.svg?react'
export { default as Like } from './icn_like.svg?react'
