export { default as Filter } from './icn_filter.svg?react'
export { default as Home } from './icn_home.svg?react'
export { default as Look } from './icn_look.svg?react'
export { default as Music } from './icn_music.svg?react'
export { default as Person } from './icn_person.svg?react'
export { default as Search } from './icn_search.svg?react'
export { default as Send } from './icn_send.svg?react'
