name: 🐞 버그 리포트
description: 발견한 버그를 보고하고 재현 방법을 설명하기 위한 이슈 템플릿입니다.

body:
  - type: textarea
    id: bug-description
    attributes:
      label: "📝 버그 설명"
      description: "발견한 버그에 대해 자세히 설명해주세요. 어떤 상황에서, 어떤 동작을 했을 때 발생했는지 포함하면 좋습니다."
      placeholder: "ex)\n- 로그인 후 메인 페이지에서 특정 버튼 클릭 시 앱이 강제 종료됩니다.\n- 상품 목록 필터 적용 시 결과가 올바르지 않습니다."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "\n&nbsp;"

  - type: textarea
    id: reproduction-steps
    attributes:
      label: "🎯 재현 방법"
      description: "버그를 재현할 수 있는 구체적인 단계를 번호 목록으로 작성해주세요."
      placeholder: |
        1. A 페이지로 이동
        2. B 버튼 클릭
        3. C 동작 수행
        4. 오류 발생 확인
    validations:
      required: true

  - type: markdown
    attributes:
      value: "\n&nbsp;"

  - type: textarea
    id: screenshots
    attributes:
      label: "📷 스크린샷"
      description: "오류 화면이나 관련 이미지가 있다면 여기에 첨부하세요. (이미지 업로드 기능은 GitHub 자체에서 제공)"
      placeholder: "여기에 스크린샷을 드래그 앤 드롭하거나 붙여넣으세요."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "\n&nbsp;"

  - type: markdown
    attributes:
      value: "\n&nbsp;"

  - type: markdown
    attributes:
      value: >
        **👇 아래의 Assignee, Label, Project, Milestone을 설정해주세요. 👇**
